{
  "openapi": "3.0.1",
  "info": {
    "title": "BiblioCat API v1",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "auth"
    },
    {
      "name": "books"
    },
    {
      "name": "authors"
    },
    {
      "name": "reading-logs"
    },
    {
      "name": "users"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "Log in a user",
        "deprecated": false,
        "description": "Log in to get a generated JWT.",
        "tags": [
          "auth"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 255
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8
                  }
                },
                "required": [
                  "username",
                  "password"
                ]
              },
              "example": {
                "username": "en999zz",
                "password": "M1IKDd68aZje6SJ"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "default": 200,
                      "minimum": 0,
                      "maximum": 999
                    },
                    "access_token": {
                      "type": "string",
                      "description": "JWT"
                    }
                  },
                  "required": [
                    "status",
                    "access_token"
                  ]
                },
                "example": {
                  "status": 200,
                  "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.ey..."
                }
              }
            },
            "headers": {}
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Register a new account",
        "deprecated": false,
        "description": "Register a new account.",
        "tags": [
          "auth"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 255
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8
                  }
                },
                "required": [
                  "username",
                  "email",
                  "password"
                ]
              },
              "example": {
                "username": "en999zz",
                "email": "en999zz2@student.lnu.se",
                "password": "M1IKDd68aZje6SJ"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "title": ""
                    },
                    "id": {
                      "type": "integer",
                      "description": "The ID of the resource",
                      "minimum": 0
                    },
                    "username": {
                      "type": "string",
                      "description": "The user's username."
                    },
                    "email": {
                      "type": "string",
                      "description": "The user's email address."
                    }
                  },
                  "required": [
                    "status",
                    "username",
                    "email",
                    "id"
                  ]
                },
                "example": {
                  "status": 201,
                  "id": 3,
                  "username": "en999zz",
                  "email": "en999zz2@student.lnu.se"
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/books/{id}": {
      "get": {
        "summary": "Find book by ID",
        "deprecated": false,
        "description": "Get a book by ID.",
        "tags": [
          "books"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the book.",
            "required": true,
            "example": 159,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Book"
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "data": {
                    "authors": [
                      {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/132",
                        "id": 132
                      }
                    ],
                    "categories": [
                      {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/6",
                        "id": 6
                      },
                      {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/25",
                        "id": 25
                      },
                      {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/85",
                        "id": 85
                      }
                    ],
                    "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                    "description": "This carefully crafted ebook: \"The Art of War (The Classic Lionel Giles Translation)” is formatted for your eReader with a functional table of contents. The Art of War is an ancient ...",
                    "href": "https://patriciaj.se/bibliocat-api/api/v1/books/159",
                    "id": 159,
                    "isbn": "9788074844553",
                    "language": "English",
                    "page_count": 80,
                    "published_date": "Sat, 02 Jun 2012 00:00:00 GMT",
                    "publisher": {
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/publishers/21",
                      "id": 21
                    },
                    "rating": 4.6,
                    "title": "The Art of War (The Classic Lionel Giles Translation)",
                    "updated_at": "Mon, 25 May 2026 13:10:50 GMT",
                    "voters": 24
                  },
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/books": {
      "get": {
        "summary": "Find books",
        "deprecated": false,
        "description": "Get a list of books using optional filters.",
        "tags": [
          "books"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 20,
              "maximum": 25,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 0,
              "minimum": 0
            }
          },
          {
            "name": "category",
            "in": "query",
            "description": "The category the book belongs to.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "title",
            "in": "query",
            "description": "The book title.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "isbn",
            "in": "query",
            "description": "The book ISBN.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "author",
            "in": "query",
            "description": "The name of the author.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "publisher",
            "in": "query",
            "description": "The name of the publisher.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "language",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "min_rating",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "number",
              "maximum": 5,
              "minimum": 0
            }
          },
          {
            "name": "max_rating",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "number",
              "maximum": 5,
              "minimum": 0
            }
          },
          {
            "name": "author_id",
            "in": "query",
            "description": "The ID of the author resource.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "The ID of the author resource",
              "minimum": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Book"
                      }
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "data": [
                    {
                      "authors": [
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/11",
                          "id": 11
                        }
                      ],
                      "categories": [
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/2",
                          "id": 2
                        },
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/11",
                          "id": 11
                        },
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/18",
                          "id": 18
                        },
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/19",
                          "id": 19
                        }
                      ],
                      "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "description": "Geralt is a witcher, a man whose magic powers, enhanced by long training and a mysterious elixir, have made him a brilliant fighter and a merciless assassin. . .",
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/books/11",
                      "id": 11,
                      "isbn": "9781473211551",
                      "language": "English",
                      "page_count": 400,
                      "published_date": "Thu, 21 May 2015 00:00:00 GMT",
                      "publisher": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/publishers/9",
                        "id": 9
                      },
                      "rating": 4.8,
                      "title": "Sword of Destiny: Witcher 2: Tales of the Witcher",
                      "updated_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "voters": 383
                    },
                    {
                      "authors": [
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/15",
                          "id": 15
                        }
                      ],
                      "categories": [
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/2",
                          "id": 2
                        },
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/11",
                          "id": 11
                        },
                        {
                          "href": "https://patriciaj.se/bibliocat-api/api/v1/categories/14",
                          "id": 14
                        }
                      ],
                      "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "description": "The Wheel of Time ® is a PBS Great American Read Selection! Now in development for TV! Since its debut in 1990, The Wheel ...",
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/books/16",
                      "id": 16,
                      "isbn": "9781429960748",
                      "language": "English",
                      "page_count": 704,
                      "published_date": "Tue, 20 Jul 2010 00:00:00 GMT",
                      "publisher": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/publishers/12",
                        "id": 12
                      },
                      "rating": 4.4,
                      "title": "Crossroads of Twilight: Book Ten of 'The Wheel of Time'",
                      "updated_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "voters": 427
                    }
                  ],
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/authors/{id}": {
      "get": {
        "summary": "Find author by ID",
        "deprecated": false,
        "description": "Find an author by ID.",
        "tags": [
          "authors"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the author.",
            "required": true,
            "example": 132,
            "schema": {
              "type": "integer",
              "minimum": 1,
              "example": 132
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "$ref": "#/components/schemas/Author"
                    }
                  },
                  "required": [
                    "data",
                    "status"
                  ]
                },
                "example": {
                  "data": {
                    "books": "https://patriciaj.se/bibliocat-api/api/v1/books?author_id=132",
                    "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                    "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/132",
                    "id": 132,
                    "name": "Sun Tzu",
                    "updated_at": "Mon, 25 May 2026 13:10:50 GMT"
                  },
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/authors": {
      "get": {
        "summary": "Filter authors",
        "deprecated": false,
        "description": "Get a list of authors using optional filters.",
        "tags": [
          "authors"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the maximum number of items to return.",
              "default": 20,
              "maximum": 25,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the starting index of the data.",
              "minimum": 0,
              "default": 0
            }
          },
          {
            "name": "name",
            "in": "query",
            "description": "The name of the author",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "book_id",
            "in": "query",
            "description": "ID of book resource",
            "required": false,
            "schema": {
              "type": "integer",
              "minimum": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Author"
                      }
                    }
                  },
                  "required": [
                    "data",
                    "status"
                  ]
                },
                "example": {
                  "data": [
                    {
                      "books": "https://patriciaj.se/bibliocat-api/api/v1/books?author_id=6",
                      "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/6",
                      "id": 6,
                      "name": "George R.R. Martin",
                      "updated_at": "Mon, 25 May 2026 13:10:50 GMT"
                    },
                    {
                      "books": "https://patriciaj.se/bibliocat-api/api/v1/books?author_id=7",
                      "created_at": "Mon, 25 May 2026 13:10:50 GMT",
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/authors/7",
                      "id": 7,
                      "name": "J.M. Barlog",
                      "updated_at": "Mon, 25 May 2026 13:10:50 GMT"
                    }
                  ],
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": []
      }
    },
    "/reading-logs": {
      "post": {
        "summary": "Create Reading log",
        "deprecated": false,
        "description": "Create a reading log to keep track of a read book.",
        "tags": [
          "reading-logs"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReadingLogPayload"
              },
              "examples": {
                "1": {
                  "value": {
                    "book_id": 159,
                    "started_at": "2026-01-31",
                    "ended_at": "2026-04-25"
                  },
                  "summary": "Example"
                },
                "2": {
                  "value": {
                    "book_id": 179,
                    "started_at": "2026-03-27"
                  },
                  "summary": "Example whithout ended_at"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 201
                    },
                    "id": {
                      "type": "integer",
                      "description": "The ID of the resource",
                      "minimum": 0
                    },
                    "href": {
                      "type": "string",
                      "description": "self-link",
                      "title": ""
                    },
                    "created_at": {
                      "type": "string",
                      "description": "The date and time when the resource was created"
                    },
                    "updated_at": {
                      "type": "string",
                      "description": "The date and time when the resource was last modified"
                    },
                    "started_at": {
                      "type": "string",
                      "description": "The date and time for when the reading started"
                    },
                    "ended_at": {
                      "type": "string",
                      "description": "The date and time for when the reading ended",
                      "nullable": true
                    },
                    "user": {
                      "description": "The user",
                      "$ref": "#/components/schemas/RelatedResource"
                    },
                    "book": {
                      "$ref": "#/components/schemas/RelatedResource",
                      "description": "The book"
                    }
                  },
                  "required": [
                    "status",
                    "id",
                    "href",
                    "created_at",
                    "updated_at",
                    "started_at",
                    "ended_at",
                    "user",
                    "book"
                  ]
                },
                "example": {
                  "book": {
                    "href": "https://patriciaj.se/bibliocat-api/api/v1/books/179",
                    "id": 179
                  },
                  "created_at": "Sun, 31 May 2026 16:46:29 GMT",
                  "ended_at": null,
                  "href": "https://patriciaj.se/bibliocat-api/api/v1/reading-logs/15",
                  "id": 15,
                  "started_at": "Sat, 30 May 2026 23:51:21 GMT",
                  "status": 201,
                  "updated_at": "Sun, 31 May 2026 16:46:29 GMT",
                  "user": {
                    "href": "https://patriciaj.se/bibliocat-api/api/v1/users/65",
                    "id": 65
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "get": {
        "summary": "Filter reading logs",
        "deprecated": false,
        "description": "Get a list of reading logs using optional filters.",
        "tags": [
          "reading-logs"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "Specifies the maximum number of items to return.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the maximum number of items to return.",
              "default": 20,
              "maximum": 25,
              "minimum": 1
            }
          },
          {
            "name": "offset",
            "in": "query",
            "description": "Specifies the starting index of the data.",
            "required": false,
            "schema": {
              "type": "integer",
              "description": "Specifies the starting index of the data.",
              "minimum": 0,
              "default": 0
            }
          },
          {
            "name": "book_id",
            "in": "query",
            "description": "The ID of the book",
            "required": false,
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          },
          {
            "name": "book_title",
            "in": "query",
            "description": "The title of the book",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Specifies the column to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "started_at",
                "ended_at",
                "created_at",
                "updated_at"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ReadingLog"
                      }
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "data": [
                    {
                      "book": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/books/159",
                        "id": 159
                      },
                      "created_at": "Sun, 31 May 2026 16:46:24 GMT",
                      "ended_at": "Sat, 30 May 2026 19:28:27 GMT",
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/reading-logs/14",
                      "id": 14,
                      "started_at": "Thu, 26 Feb 2026 04:20:19 GMT",
                      "updated_at": "Sun, 31 May 2026 16:46:24 GMT",
                      "user": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/users/65",
                        "id": 65
                      }
                    },
                    {
                      "book": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/books/179",
                        "id": 179
                      },
                      "created_at": "Sun, 31 May 2026 16:46:29 GMT",
                      "ended_at": null,
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/reading-logs/15",
                      "id": 15,
                      "started_at": "Sat, 30 May 2026 23:51:21 GMT",
                      "updated_at": "Sun, 31 May 2026 16:46:29 GMT",
                      "user": {
                        "href": "https://patriciaj.se/bibliocat-api/api/v1/users/65",
                        "id": 65
                      }
                    }
                  ],
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/reading-logs/{id}": {
      "get": {
        "summary": "Find reading log by ID",
        "deprecated": false,
        "description": "Get a specific reading log.",
        "tags": [
          "reading-logs"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the reading log",
            "required": true,
            "example": 1,
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "minimum": 0,
                      "maximum": 999,
                      "default": 200
                    },
                    "data": {
                      "$ref": "#/components/schemas/ReadingLog"
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "data": {
                    "book": {
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/books/159",
                      "id": 159
                    },
                    "created_at": "Thu, 21 May 2026 20:36:21 GMT",
                    "ended_at": "Thu, 21 May 2026 01:36:17 GMT",
                    "href": "https://patriciaj.se/bibliocat-api/api/v1/reading-logs/7",
                    "id": 7,
                    "started_at": "Tue, 23 Dec 2025 17:39:08 GMT",
                    "updated_at": "Thu, 21 May 2026 20:36:21 GMT",
                    "user": {
                      "href": "https://patriciaj.se/bibliocat-api/api/v1/users/8",
                      "id": 8
                    }
                  },
                  "status": 200
                }
              }
            },
            "headers": {}
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "summary": "Update a ReadingLog",
        "deprecated": false,
        "description": "Edit a reading log.",
        "tags": [
          "reading-logs"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the reading log.",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReadingLogPayload"
              },
              "example": {
                "book_id": 159,
                "started_at": "2026-01-31",
                "ended_at": "2026-05-30"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "The server successfully processed the request and is not returning any content.",
            "headers": {}
          },
          "400": {
            "$ref": "#/components/responses/Bad Request",
            "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "Delete a Reading Log",
        "deprecated": false,
        "description": "Delete a reading log by ID. Requires authentication.",
        "tags": [
          "reading-logs"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the reading log.",
            "required": true,
            "schema": {
              "type": "integer",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The server successfully processed the request and is not returning any content.",
            "headers": {}
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/users/{id}": {
      "delete": {
        "summary": "Delete a user",
        "deprecated": false,
        "description": "Delete a user by ID. Requires authentication.  \nReading logs owned by the user will also be deleted.",
        "tags": [
          "users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the user.",
            "required": true,
            "schema": {
              "type": "integer",
              "description": "The ID of the user",
              "minimum": 1
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The server successfully processed the request and is not returning any content.",
            "headers": {}
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized",
            "description": "Credentials invalid or not provided."
          },
          "404": {
            "$ref": "#/components/responses/Not Found",
            "description": "The requested resource was not found."
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error",
            "description": "The server encountered an unexpected condition that prevented it from fulfilling the request."
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/health": {
      "get": {
        "summary": "API health check",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "description": "HTTP status code",
                      "default": 200
                    },
                    "message": {
                      "type": "string",
                      "description": "Description",
                      "title": "",
                      "default": "OK"
                    }
                  },
                  "required": [
                    "message",
                    "status"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "Author": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource",
            "minimum": 0
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "name": {
            "type": "string",
            "description": "Name of the author"
          },
          "books": {
            "type": "string",
            "description": "URL to filtered books collection"
          }
        },
        "required": [
          "name",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "BaseResource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource",
            "minimum": 0
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          }
        },
        "required": [
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "ReadingLog": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource",
            "minimum": 0
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "started_at": {
            "type": "string",
            "description": "The date and time for when the reading started"
          },
          "ended_at": {
            "type": "string",
            "description": "The date and time for when the reading ended",
            "nullable": true
          },
          "user": {
            "description": "The user",
            "$ref": "#/components/schemas/RelatedResource"
          },
          "book": {
            "$ref": "#/components/schemas/RelatedResource",
            "description": "The book"
          }
        },
        "required": [
          "started_at",
          "ended_at",
          "user",
          "book",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      },
      "RelatedResource": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource",
            "minimum": 1
          },
          "href": {
            "type": "string",
            "description": "Link to the resource",
            "title": ""
          }
        },
        "required": [
          "id",
          "href"
        ]
      },
      "ReadingLogPayload": {
        "type": "object",
        "properties": {
          "book_id": {
            "type": "integer",
            "description": "The ID of the book",
            "minimum": 1
          },
          "started_at": {
            "type": "string",
            "description": "The date and time for when the reading started"
          },
          "ended_at": {
            "type": "string",
            "description": "The date and time for when the reading ended",
            "nullable": true
          }
        },
        "required": [
          "started_at",
          "book_id"
        ]
      },
      "Book": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "The ID of the resource",
            "minimum": 0
          },
          "href": {
            "type": "string",
            "description": "self-link",
            "title": ""
          },
          "created_at": {
            "type": "string",
            "description": "The date and time when the resource was created"
          },
          "updated_at": {
            "type": "string",
            "description": "The date and time when the resource was last modified"
          },
          "title": {
            "type": "string"
          },
          "authors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            },
            "description": "The author(s) of the book."
          },
          "isbn": {
            "type": "string"
          },
          "publisher": {
            "$ref": "#/components/schemas/RelatedResource",
            "description": "The publisher."
          },
          "published_date": {
            "type": "string"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RelatedResource"
            },
            "description": "The categories the book belongs to."
          },
          "description": {
            "type": "string"
          },
          "language": {
            "type": "string"
          },
          "page_count": {
            "type": "integer"
          },
          "rating": {
            "type": "number",
            "minimum": 0,
            "maximum": 5
          },
          "voters": {
            "type": "integer",
            "minimum": 0,
            "description": "The number of reviewers."
          }
        },
        "required": [
          "title",
          "id",
          "href",
          "created_at",
          "updated_at"
        ]
      }
    },
    "responses": {
      "Bad Request": {
        "description": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error).",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "minimum": 0,
                  "maximum": 999,
                  "default": 400
                },
                "message": {
                  "type": "string",
                  "description": "Error description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 400,
                  "message": "The request cannot or will not be processed due to something that is perceived to be a client error (for example validation error)."
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Credentials invalid or not provided.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 401,
                  "minimum": 0,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "title": "",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 401,
                  "message": "Credentials invalid or not provided."
                }
              }
            }
          }
        }
      },
      "Internal Server Error": {
        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 500,
                  "minimum": 0,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 500,
                  "message": "The server encountered an unexpected condition that prevented it from fulfilling the request."
                }
              }
            }
          }
        }
      },
      "Not Found": {
        "description": "The requested resource was not found.",
        "content": {
          "application/json": {
            "schema": {
              "title": "",
              "type": "object",
              "properties": {
                "status": {
                  "type": "integer",
                  "description": "HTTP status code",
                  "default": 404,
                  "minimum": 1,
                  "maximum": 999
                },
                "message": {
                  "type": "string",
                  "title": "",
                  "description": "Description"
                }
              },
              "required": [
                "status",
                "message"
              ]
            },
            "examples": {
              "Default": {
                "summary": "Default",
                "value": {
                  "status": 404,
                  "message": "The requested resource was not found."
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [
    {
      "url": "https://patriciaj.se/bibliocat-api/api/v1",
      "description": "Prod Env"
    }
  ],
  "security": []
}